### PR TITLE
Resource list

### PR DESCRIPTION
**Pull request by ForNeVeR**
Create a resource list according to #15.

Also I removed all Google Analytics references because we do not track our users and do not want to.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
cc @rexim

**Comment by rexim** [comment]
Mixer disapproves the shit that builds with errors.

**Comment by ForNeVeR** [comment]
That shit builds perfectly. That's Travis who cannot into Yesod. There is a task to teach him: #19.

**Comment by rexim** [comment]
I approve this shit! \o/

**Pull request merged**
