### PR TITLE
Repair Travis build

### LINKED ISSUE #19: Repair Travis integration
Travis cannot build our project due to some `happy` issues. It should be fixed.

### PR DESCRIPTION
**Pull request by ForNeVeR**
Close #19.

### CODE REVIEW

**Comment by rexim** [comment]
:D

**Comment by ForNeVeR** [comment]
Well, that went good so far, now it is properly installed. All we want is to add a small postgresql instance.

**Comment by ForNeVeR** [comment]
@rexim, you want to approve that **glorious** piece of shit.

**Comment by ForNeVeR** [comment]
Ah, wait, I've found another issue...

**Comment by ForNeVeR** [comment]
Yeah, @rexim, you may check this piece of *glory* now.

**Comment by rexim** [comment]
I approve it! :)

**Pull request merged**
